# ======== Users section 
### post user 
POST http://localhost:8002/api/v1/employees
Content-Type: application/json

{
    "fName":"Anil",
    "mName":"tamang",
    "lName":"tamang",
    "dob":"2024-05-22T09:36:19.000+00:00",
    "gender":"male",
    "phone":"47657456",
    "email":"anil7777@gmail.com",
    "department":"doctor",
    "jobTitle":"Dr",
    "startDate":"2024-05-22T09:36:19.000+00:00",
    "employmentType":"casual",
    "employeeId":"yrhfjkdnd"
      
}

###get user
GET http://localhost:8002/api/v1/employees
Content-Type: application/json

### post user 
POST http://localhost:8002/api/v1/users/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123"
}

